### ISSUE TITLE
[wiki] Fix return type of sumElements

### ISSUE THREAD

**Issue by stites** [mstksg/backprop#4]
Above [Multiple-argument functions](https://github.com/mstksg/backprop/wiki/Equipping-your-Library-with-Backprop#multiple-argument-functions) the function signatures of `sumElements` should be:

```
sumElements :: Reifies s W => BVar s (R n) -> BVar s Double
```

I tried to submit a PR to the wiki, but I don't think it's possible! I know that page is currently a work in progress, but this one might have slipped through.

**Comment by mstksg** [comment]
Thanks for the catch!  This is my first time using github wiki's and I didn't realize that allowing non-collaborators to edit was opt-in.  I think all users should be allowed to edit now!
