### ISSUE TITLE
[wiki] add note about wiki being written for backprop >=0.2.0

### ISSUE THREAD

**Issue by stites** [mstksg/backprop#5]
I still seem to have some issues pushing to the wiki. Maybe write access is for contributors only?

**Comment by mstksg** [comment]
Hm, I've followed the directions on https://help.github.com/articles/changing-access-permissions-for-wikis/ and unchecked the editing restriction.    Are you able to make new pages from the main page?

**Comment by stites** [comment]
Yup! it's working. I think it might have just been a hiccup pushing from my local, but changes can be made via the github website.
