### ISSUE TITLE
Why not have an undecidable instance Num a => Backprop a ?

### ISSUE THREAD

**Issue by stites** [mstksg/backprop#6]
which would be satisfied with the `*Num` functions?

**Comment by mstksg** [comment]
This would make *all* instances ever for `Backprop` be overlapping instances, even for types that don't have `Num` instances, which is a bit too dangerous/playing with fire -- definitely not something that the haskell type system was designed to handle, heh.

An alternative nice solution would probably leverage `DerivingVia`  when that extension lands (ghc-proposals/ghc-proposals#120) to allow deriving with Num or Generics.

**Comment by mstksg** [comment]
It also precludes the possibility of a type implementing its own instance of Backprop if it has a Num instance, even if there is a potentially faster implementation than `addNum`/`zeroNum`/`oneNum`

**Comment by stites** [comment]
:+1: yup, makes sense!
